### ISSUE TITLE
ImportError while running rdbms-subsetter

### ISSUE THREAD

**Issue by pooja8bhatt** [18F/rdbms-subsetter#40]
Getting import error trying to run the most basic command. 
```: rdbms-subsetter postgresql://abc:xyz@localhost/db_name postgresql://abc:xyz@127.0.0.1/db_name2
Traceback (most recent call last):
  File "/usr/local/bin/rdbms-subsetter", line 7, in <module>
    from subsetter import generate
  File "/usr/local/lib/python2.7/dist-packages/subsetter.py", line 75, in <module>
    from dialects.postgres import fix_postgres_array_of_enum
ImportError: No module named dialects.postgres
```

**Comment by sebboh** [comment]
It looks like the project is not being actively maintained, but for anyone else that comes across this error I found a workaround to get this running. I'm not a python dev so maybe I missed something, but for whatever reason pip does not seem to install all of the project files. You need to copy the `dialects` folder of this project to your python `site-packages` folder. For me, this meant cloning the repository and linking dialects to `/usr/local/lib/python2.7/site-packages`
